name: Build and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push changes
        run: |
          git config user.name "Nazmus Sayad"
          git config user.email "87106526+NazmusSayad@users.noreply.github.com"
          git add .
          git commit -m "Auto-build by GitHub Actions"
          git push
