name: Package and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'snippets/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install packages
        run: npm install

      - name: Build the extension
        run: npm run build-ext

      - name: Publish
        run: |
          cd ./dist-extension
          npx vsce package
          npx vsce publish -p ${{ secrets.AZURE_PUBLISH_TOKEN }}
